### ISSUE TITLE
Cannot answer call after '183 Session Progress'

### ISSUE THREAD

**Issue by MayamaTakeshi** [MayamaTakeshi/sip-lab#65]
```
pjw_call_respond: call_id=1 json={"code":200,"reason":"OK"}

Error: no pending request to be answered
    at Object.respond (/home/takeshi/src/git/MayamaTakeshi/sip-lab/index.js:58:45)
    at test (/home/takeshi/src/git/MayamaTakeshi/sip-lab/samples/183_session_progress.js:110:14)
    at process.processTicksAndRejecti
```

**Comment by MayamaTakeshi** [comment]
This was originally possible. It started to fail after #42.
