### ISSUE TITLE
Cannot create more than 16 calls

### ISSUE THREAD

**Issue by MayamaTakeshi** [MayamaTakeshi/sip-lab#66]
If we change
```
const NUMBER_OF_CALLS = 16
```
to 
```
const NUMBER_OF_CALLS = 17
``` 
in https://github.com/MayamaTakeshi/sip-lab/blob/0e336a738038a3533d2dff494dba419ff22136f1/samples/16_calls.js

the test will fail with:
```
json_get_string_param reason
process_media call_id=32
i=0 media not found

create_media_endpoint call_id=32
Error: create_media_transport failed
    at Object.respond (/home/takeshi/src/git/MayamaTakeshi/sip-lab/index.js:58:45)
    at /home/takeshi/src/git/MayamaTakeshi/sip-lab/a.js:55:18
    at Array.forEach (<anonymous>)
    at test (/home/takeshi/src/git/MayamaTakeshi/sip-lab/a.js:54:20)
```

**Comment by MayamaTakeshi** [comment]
Changing to use a single transport for caller and another for callee doesn't change behavior:
```
json_get_string_param reason
process_media call_id=32
i=0 media not found

create_media_endpoint call_id=32
Error: create_media_transport failed
    at Object.respond (/home/takeshi/src/git/MayamaTakeshi/sip-lab/index.js:58:45)
    at /home/takeshi/src/git/MayamaTakeshi/sip-lab/a.js:50:18
    at Array.forEach (<anonymous>)
    at test (/home/takeshi/src/git/MayamaTakeshi/sip-lab/a.js:49:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
